version: '2'

services:
  dibimbing-dataeng-jupyter:
    container_name: ${JUPYTER_CONTAINER_NAME}
    hostname: ${JUPYTER_CONTAINER_NAME}
    image: dataeng-dibimbing/jupyter
    environment:
      - JUPYTER_ALLOW_INSECURE_WRITES=true
    ports:
      - ${JUPYTER_PORT}:8888
#      - 4040:4040
#      - 4041:4041
    volumes:
      - ../:/resources
      - ../notebooks:/home/jovyan/

networks:
  default:
    name: dataeng-network
    external: true

# 0a1ece58defb4189a7cea2e6fe2bdbd37e42d96821e2b5e8